<FirstScreen>:
    FloatLayout:
    
        MDLabel:
            pos_hint: {"x": .3, "top": .98}
            size_hint: (.4, .1)
            haling: "center"
            font_style: "H5"
            text: "Primera Pantalla"
            
        MDRectangleFlatIconButton:
            halign: "center"
            icon: "android"
            pos_hint: {"x": .3, "top": .5}
            size_hint: (.4, .1)
            text: "comercios"
        