<SettingsScreen>:
    
    FloatLayout:
            
        MDLabel:
            pos_hint: {"x": .15,"top": .99 }
            size_hint: (.2, .1)
            text: "Modo Nocturno"
            haling: "center"
            theme_text_color: "Primary"

        MDLabel:
            pos_hint: {"x": .16,"top": .9 }
            size_hint: (.2, .1)
            text: "Selecciona un Tema "
            haling: "center"
            theme_text_color: "Primary"

        MDLabel:
            pos_hint: {"x": .5,"top": .9 }
            size_hint: (.2, .1)
            text: "Colores Disponibles"
            haling: "center"
            theme_text_color: "Primary"

        MDLabel:
            pos_hint: {"x": .78,"top": .9 }
            size_hint: (.2, .1)
            text: "Intensidad del Color"
            haling: "center"
            theme_text_color: "Primary"

        MDLabel:
            pos_hint: {"x": .2,"top": .5 }
            size_hint: (.8, .1)
            text: "Respalda, Descarga tu inventario o Borra los elementos de la App"
            haling: "center"
            theme_text_color: "Primary"

        MDIconButton:
            pos_hint: {"x": .15,"top": .4 }
            size_hint: (.2, .1)
            icon: "file-upload-outline"
            on_release: root.subir_archivo()

        MDLabel:
            id: subir
            pos_hint: {"x": .4,"top": .4 }
            size_hint: (.5,.1)
            text: "Respaldar Inventario en Drive"
            theme_text_color: "Primary"

        MDIconButton:
            pos_hint: {"x": .15,"top": .3 }
            size_hint: (.2, .1)
            icon: "file-download-outline"
            on_release: root.descargar_archivo()

        MDLabel:
            id: descargar
            pos_hint: {"x": .4,"top": .3 }
            size_hint: (.5,.1)
            text: "Descargar Inventario desde Drive"
            theme_text_color: "Primary"

        MDIconButton:
            pos_hint: {"x": .15,"top": .2 }
            size_hint: (.2, .1)
            icon: "delete-alert"
            on_release: root.borrar_archivo()

        MDLabel:
            id: eliminar
            pos_hint: {"x": .4,"top": .2 }
            size_hint: (.5,.1)
            text: "Eliminar datos del Drive"
            theme_text_color: "Primary"




            
           
        
            
        
        